### ISSUE TITLE
To/Cc/Bcc の区切りが分かりやすいようにする

### ISSUE THREAD

**Issue by ykinoshi1015** [ykinoshi1015/OutlookRecipientConfirmationAddin#1]
「=====To:1件=====」みたいにする。

**Comment by YunaNakanishi** [comment]
![1](https://user-images.githubusercontent.com/29644865/34286785-52dae848-e726-11e7-9fad-bc5be8eafeaf.png)
![2](https://user-images.githubusercontent.com/29644865/34286786-53071ef4-e726-11e7-8c6c-965474c9ad27.png)
![3](https://user-images.githubusercontent.com/29644865/34286787-532b8870-e726-11e7-906b-3e11f313fe49.png)

**Comment by YunaNakanishi** [comment]
こんな区切りはどうですか？
どれがいいとかありますか？

**Comment by ykinoshi1015** [comment]
こんな感じでいいと思います。
中西さんのセンスで決めちゃってください！

**Comment by YunaNakanishi** [comment]
わかりました！

**Comment by ykinoshi1015** [comment]
確認しました。OKです。
