### ISSUE TITLE
エラーダイアログの実装

### ISSUE THREAD

**Issue by ykinoshi1015** [ykinoshi1015/OutlookRecipientConfirmationAddin#18]
例外をcatchしたときに表示するダイアログ。
Labelにメッセージ、その下にTextBoxを配置してスタックトレースを載せる。
ダイアログはResize可能とする。

**Comment by YunaNakanishi** [comment]
エラーダイアログを表示するのは、メール送信時の宛先確認の時だけですか？
それとも、受信メールなどの宛先表示の時もですか？

**Comment by ykinoshi1015** [comment]
「メール送信時の宛先確認の時だけ」にしたときに、
受信メールの宛先表示だけで例外が起こってユーザーから連絡があった場合に
開発者（中西さん）が困らないかどうかで、どうするか決められると思うよ！

**Comment by YunaNakanishi** [comment]
なるほど、宛先表示のときもあったほうがいいですね！

**Comment by ykinoshi1015** [comment]
そうだね、両方ともちゃんとしたエラーダイアログを出すほういいですね。
