### ISSUE TITLE
インストール時&アドイン起動時にレジストリの「アドイン無効化しない」をONにする

### ISSUE THREAD

**Issue by ykinoshi1015** [ykinoshi1015/OutlookRecipientConfirmationAddin#41]
## 処理の概要
レジストリをチェックし、無効化しない設定がされていなければ、アドイン無効化しないようレジストキーを追加・設定する

## 処理のタイミング
* インストール時に実行するaddinScript.bat
  * DoNotDisableAddinUpdater.exeを実行する
    * DoNotDisableAddinUpdater.dllの関数を呼び出す
* ThisAddIn_Startup()
  * DoNotDisableAddinUpdater.dllの関数を呼び出す

## VisualStudioソリューションの構成
OutlookRecipientComfirmationAddin.slnの中に以下のプロジェクト(csproj)を追加する
1. DoNotDisableAddinUpdater.exeのC#コンソールアプリケーション
2. DoNotDisableAddinUpdater.dllのC#クラスライブラリ

## 気になる事
* 管理者権限を持ってるユーザーでOutlook起動したときに、レジストリ書き込みできるか？
* 管理者権限を持ってないユーザーでOutlook起動したときに、レジストリ書き込みできるか？

**Comment by ykinoshi1015** [comment]
もしPowerShell から直接.NETのDLLを呼び出せるなら、exeは要らないかなぁ。
(PowerShellスクリプトをexeの代用にする)

**Comment by YunaNakanishi** [comment]
PowerShell:hushed:
よくわからないので、明日調べますね。

**Comment by YunaNakanishi** [comment]
Windows7で、O365をインストール済みでも、Resiliencyの下にDoNotDisableAddinListがない
![win7_registry](https://user-images.githubusercontent.com/29644865/36579962-71de0946-18a9-11e8-87bc-5824b9503133.PNG)

→ DoNotDisableAddinListが無い場合、作成し、その中でOutlookRecipientConfirmationAddinの値を「１」に設定する

**Comment by YunaNakanishi** [comment]
Windows7の場合、インストール時にpowershellのエラー文が表示される
![win7_runtime_error](https://user-images.githubusercontent.com/29644865/36580069-ef9a199c-18a9-11e8-87c7-645bacb33028.PNG)

**Comment by YunaNakanishi** [comment]
発行時の「対象のフレームワーク」： .NET Framework 4.5.2
Win7 Virtual Boxでインストールされているバージョン： 4.7.1 (レジストリから確認)
Win10 Virtual Boxでインストールされているバージョン： 4.7 (レジストリから確認)

Windows7:
![win7_dotnet](https://user-images.githubusercontent.com/29644865/36582071-48f10506-18b3-11e8-88c7-4d3ec6744dbe.PNG)

Windows10:
![win10_dotnet](https://user-images.githubusercontent.com/29644865/36582045-2c7e946a-18b3-11e8-9941-9878d6427c24.PNG)

Windows7で、4.7.1ではないバージョンの.NET Frameworkが読み込まれているから、赤いエラー文がでるのかも？
だとしたら、どこで使うランタイムを変えられる？

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
 @ykinoshi1015 さん(or @kksk-github )、ヘルプお願いします！！

**Comment by ykinoshi1015** [comment]
まず、PowerShellが参照している.NETのバージョンを調べてみよう。
PowerShellのコンソールを起動して、「$PSVersionTable」って入力・実行してみて。

**Comment by YunaNakanishi** [comment]
$PSVersionTableのCLRVerisonが
Windows7: 2.0.50727.8762
Windows10:  4.0.30319.42000
でした。これが原因のようですね:weary:
