### ISSUE TITLE
OutlookでNotesリンクのクリック時にでる警告を抑制するキーが作成されない

### ISSUE THREAD

**Issue by YunaNakanishi** [ykinoshi1015/OutlookRecipientConfirmationAddin#54]
<img width="453" alt="regedit_notes" src="https://user-images.githubusercontent.com/29644865/36359920-e24b6ede-1562-11e8-8def-a1cebe06b822.PNG">

16.0の下にCommonキーがないので
DisableProtocolSecurityPopupメソッドの一つ目のtry～catchに入ってしまい、何もされない？

**Comment by ykinoshi1015** [comment]
この機能は搭載しないためCloseにする。
