### ISSUE TITLE
送信時と宛先表示リボンの画面のバランスが悪い

### ISSUE THREAD

**Issue by YunaNakanishi** [ykinoshi1015/OutlookRecipientConfirmationAddin#57]
<img width="692" alt="ribbon" src="https://user-images.githubusercontent.com/29644865/36459166-0bbfdc84-16f6-11e8-8199-69f8edfd05bd.PNG">
<img width="690" alt="send" src="https://user-images.githubusercontent.com/29644865/36459167-0be8fb5a-16f6-11e8-9018-1ddbfc53a4aa.PNG">

**Comment by ykinoshi1015** [comment]
ディスプレイ設定の拡大率が100%より大きい環境のVisualStudioデザイナーを使っていると、こうなることがある。
(たぶんVisualStudioのバグ)
いったん拡大率を100%に戻して、サイズ調整して、ビルドしてやれば直ると思います。
