### ISSUE TITLE
アドレス帳にないメールアドレスの表示形式を、outlookの形式と統一する

### ISSUE THREAD

**Issue by YunaNakanishi** [ykinoshi1015/OutlookRecipientConfirmationAddin#82]
アドレス帳にないメールアドレスの表示形式

表示名 → 表示名＜メールアドレス＞に変更

![3](https://user-images.githubusercontent.com/29644865/37018677-9693523e-2158-11e8-89de-2758d5881c4e.PNG)

**Comment by ykinoshi1015** [comment]
対応完了。
v1.1.0.3でリリースする。
