### ISSUE TITLE
配信不能メールの宛先確認ボタンを押すと、エラーダイアログが表示される

### ISSUE THREAD

**Issue by YunaNakanishi** [ykinoshi1015/OutlookRecipientConfirmationAddin#83]
・グループアドレスに送った一部のメンバーがすでにユーザ登録から外れていて配信エラーでかえっきた場合に、表示されると報告あり

Exchangeサーバーで存在しない「XXXX@jp.ricoh.com」に送信すると、返ってくるメール↓

![4](https://user-images.githubusercontent.com/29644865/37018760-e313a83e-2158-11e8-8abf-9782f4706a33.PNG)

**Comment by ykinoshi1015** [comment]
対応完了。リリーステスト中。

**Comment by YunaNakanishi** [comment]
・Utility.GetSenderInfomationメソッド
ReportItemの場合の送信者を取得する処理がないため、宛先確認画面で「送信者」が空欄になる

・Utility.GetRecipientsメソッド
recipients = newMailItem.Recipients;　（98行目）
で取得されるRecipientsは、「配信が失敗したメール」のRecipients.
表示したい「配信不能メール」のRecipientsではない模様
